#![no_std]
use soroban_sdk::{contract, contractimpl, contracttype, Address, Env, Symbol};

#[contract]
pub struct SolarKwhToken;

#[contracttype]
#[derive(Clone)]
pub struct Installation {
    pub producer: Address,
    pub capacity_kw: u32,
    pub location_hash: u64,
    pub oracle: Address,
    pub active: bool,
    pub total_reported_kwh: u32,
    pub total_minted_kwh: u32,
}

#[contracttype]
#[derive(Clone)]
pub enum DataKey {
    Installation(Symbol),
    ReportedPeriod(Symbol, Symbol),
    Balance(Symbol, Address),
    TotalRedeemed(Symbol, Address),
}

#[contractimpl]
impl SolarKwhToken {
    /// Register a new solar installation under a unique `install_id`.
    /// The `producer` becomes the on-chain owner, and the designated
    /// `oracle` is the only address permitted to file generation reports
    /// for this installation. `location_hash` is an opaque reference
    /// (e.g. a hash of the geocoordinates) so that privacy is preserved.
    pub fn register_installation(
        env: Env,
        producer: Address,
        install_id: Symbol,
        capacity_kw: u32,
        location_hash: u64,
        oracle: Address,
    ) {
        producer.require_auth();

        if capacity_kw == 0 {
            panic!("capacity_kw must be greater than zero");
        }

        let key = DataKey::Installation(install_id.clone());
        if env.storage().instance().has(&key) {
            panic!("installation already registered");
        }

        let installation = Installation {
            producer: producer.clone(),
            capacity_kw,
            location_hash,
            oracle,
            active: true,
            total_reported_kwh: 0,
            total_minted_kwh: 0,
        };

        env.storage().instance().set(&key, &installation);
    }

    /// Authorised `oracle` reports `kwh` units generated by `install_id`
    /// for a particular `period` (e.g. "2024Q1", "202406"). Each period
    /// may only be reported once for an installation, so the report
    /// history is tamper-evident.
    pub fn report_generation(
        env: Env,
        oracle: Address,
        install_id: Symbol,
        period: Symbol,
        kwh: u32,
    ) {
        oracle.require_auth();

        let install_key = DataKey::Installation(install_id.clone());
        let mut installation: Installation = env
            .storage()
            .instance()
            .get(&install_key)
            .expect("installation not found");

        if installation.oracle != oracle {
            panic!("caller is not the authorized oracle");
        }

        if !installation.active {
            panic!("installation is inactive");
        }

        if kwh == 0 {
            panic!("kwh must be greater than zero");
        }

        let period_key = DataKey::ReportedPeriod(install_id.clone(), period);
        if env.storage().instance().has(&period_key) {
            panic!("period already reported");
        }

        installation.total_reported_kwh = installation
            .total_reported_kwh
            .checked_add(kwh)
            .expect("reported total overflow");
        env.storage().instance().set(&install_key, &installation);
        env.storage().instance().set(&period_key, &kwh);
    }

    /// Mint `kwh` units of energy tokens into the producer's balance for
    /// the given installation. The total minted across all calls cannot
    /// exceed the total kWh reported by the oracle, anchoring every token
    /// in real measured generation.
    pub fn mint_tokens(
        env: Env,
        producer: Address,
        install_id: Symbol,
        kwh: u32,
    ) {
        producer.require_auth();

        if kwh == 0 {
            panic!("kwh must be greater than zero");
        }

        let install_key = DataKey::Installation(install_id.clone());
        let mut installation: Installation = env
            .storage()
            .instance()
            .get(&install_key)
            .expect("installation not found");

        if installation.producer != producer {
            panic!("caller is not the installation producer");
        }

        if !installation.active {
            panic!("installation is inactive");
        }

        let new_total = installation
            .total_minted_kwh
            .checked_add(kwh)
            .expect("mint total overflow");

        if new_total > installation.total_reported_kwh {
            panic!("insufficient reported generation to mint");
        }

        installation.total_minted_kwh = new_total;
        env.storage().instance().set(&install_key, &installation);

        let balance_key = DataKey::Balance(install_id, producer);
        let current: u32 = env
            .storage()
            .instance()
            .get(&balance_key)
            .unwrap_or(0u32);
        let updated = current.checked_add(kwh).expect("balance overflow");
        env.storage().instance().set(&balance_key, &updated);
    }

    /// Record consumer off-take: move `kwh` units from the installation
    /// producer's balance into the consumer's balance. The producer must
    /// still have at least `kwh` un-redeemed minted tokens available, and
    /// a running per-consumer off-take tally is kept for analytics.
    pub fn redeem(
        env: Env,
        consumer: Address,
        install_id: Symbol,
        kwh: u32,
    ) {
        consumer.require_auth();

        if kwh == 0 {
            panic!("kwh must be greater than zero");
        }

        let install_key = DataKey::Installation(install_id.clone());
        let installation: Installation = env
            .storage()
            .instance()
            .get(&install_key)
            .expect("installation not found");

        if !installation.active {
            panic!("installation is inactive");
        }

        let producer = installation.producer.clone();

        let producer_balance_key = DataKey::Balance(install_id.clone(), producer.clone());
        let producer_balance: u32 = env
            .storage()
            .instance()
            .get(&producer_balance_key)
            .unwrap_or(0u32);

        if producer_balance < kwh {
            panic!("insufficient producer balance");
        }

        env.storage()
            .instance()
            .set(&producer_balance_key, &(producer_balance - kwh));

        let consumer_balance_key = DataKey::Balance(install_id.clone(), consumer.clone());
        let consumer_balance: u32 = env
            .storage()
            .instance()
            .get(&consumer_balance_key)
            .unwrap_or(0u32);
        let new_consumer_balance = consumer_balance
            .checked_add(kwh)
            .expect("balance overflow");
        env.storage()
            .instance()
            .set(&consumer_balance_key, &new_consumer_balance);

        // Track cumulative off-take per consumer for the installation
        let redeemed_key = DataKey::TotalRedeemed(install_id, consumer);
        let current_redeemed: u32 = env
            .storage()
            .instance()
            .get(&redeemed_key)
            .unwrap_or(0u32);
        let updated_redeemed = current_redeemed
            .checked_add(kwh)
            .expect("redeem total overflow");
        env.storage().instance().set(&redeemed_key, &updated_redeemed);
    }

    /// Returns the kWh token balance currently held by `holder` for the
    /// given installation. Returns 0 if the holder has no entry.
    pub fn get_balance(env: Env, holder: Address, install_id: Symbol) -> u32 {
        let key = DataKey::Balance(install_id, holder);
        env.storage().instance().get(&key).unwrap_or(0u32)
    }

    /// Returns true if `install_id` is registered on-chain and currently
    /// marked as active; false if the installation is unknown or inactive.
    pub fn is_valid_installation(env: Env, install_id: Symbol) -> bool {
        let key = DataKey::Installation(install_id);
        if let Some(install) = env
            .storage()
            .instance()
            .get::<DataKey, Installation>(&key)
        {
            install.active
        } else {
            false
        }
    }
}
